use std::path::Path;

use crate::models::collection::RequestFile;
use crate::storage::collection;

use super::DocsFormat;

struct DocRequest {
    folder: String,
    request: RequestFile,
}

pub fn generate_docs(
    collection_path: &str,
    format: &DocsFormat,
) -> Result<String, String> {
    let path = Path::new(collection_path);
    let mut requests: Vec<DocRequest> = Vec::new();

    // Walk the collection directory
    walk_requests(path, path, "", &mut requests)?;

    if requests.is_empty() {
        return Err("No requests found in collection".to_string());
    }

    let collection_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "API Documentation".to_string());

    match format {
        DocsFormat::Html => Ok(generate_html(&collection_name, &requests)),
        DocsFormat::Markdown => Ok(generate_markdown(&collection_name, &requests)),
    }
}

fn walk_requests(
    root: &Path,
    dir: &Path,
    folder_name: &str,
    requests: &mut Vec<DocRequest>,
) -> Result<(), String> {
    if !dir.exists() || !dir.is_dir() {
        return Ok(());
    }

    for entry in std::fs::read_dir(dir).map_err(|e| format!("Read dir error: {e}"))? {
        let entry = entry.map_err(|e| format!("Dir entry error: {e}"))?;
        let path = entry.path();

        if path.is_dir() {
            let name = path
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default();

            // Skip hidden dirs
            if name.starts_with('.') {
                continue;
            }

            let sub_folder = if folder_name.is_empty() {
                name
            } else {
                format!("{folder_name}/{name}")
            };
            walk_requests(root, &path, &sub_folder, requests)?;
        } else if path
            .extension()
            .map(|e| e == "yaml" || e == "yml")
            .unwrap_or(false)
        {
            // Skip folder config and hidden files
            let fname = path
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default();
            if fname.starts_with('_') || fname.starts_with('.') {
                continue;
            }

            if let Ok(request) = collection::read_request(&path) {
                requests.push(DocRequest {
                    folder: folder_name.to_string(),
                    request,
                });
            }
        }
    }

    Ok(())
}

fn generate_markdown(collection_name: &str, requests: &[DocRequest]) -> String {
    let mut md = String::new();
    md.push_str(&format!("# {collection_name}\n\n"));
    md.push_str(&format!(
        "*Generated by ApiArk on {}*\n\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    md.push_str("---\n\n");

    // Group by folder
    let mut current_folder = String::new();

    for doc in requests {
        if doc.folder != current_folder {
            current_folder = doc.folder.clone();
            if !current_folder.is_empty() {
                md.push_str(&format!("## {}\n\n", current_folder));
            }
        }

        let req = &doc.request;
        let method = format!("{:?}", req.method).to_uppercase();

        md.push_str(&format!("### {} `{}`\n\n", method, req.url));

        if let Some(desc) = &req.description {
            if !desc.is_empty() {
                md.push_str(&format!("{desc}\n\n"));
            }
        }

        // Headers
        if !req.headers.is_empty() {
            md.push_str("**Headers:**\n\n");
            md.push_str("| Header | Value |\n|--------|-------|\n");
            for (k, v) in &req.headers {
                md.push_str(&format!("| `{k}` | `{v}` |\n"));
            }
            md.push('\n');
        }

        // Query params
        if let Some(params) = &req.params {
            if !params.is_empty() {
                md.push_str("**Query Parameters:**\n\n");
                md.push_str("| Parameter | Value |\n|-----------|-------|\n");
                for (k, v) in params {
                    md.push_str(&format!("| `{k}` | `{v}` |\n"));
                }
                md.push('\n');
            }
        }

        // Body
        if let Some(body) = &req.body {
            if !body.content.is_empty() {
                md.push_str(&format!("**Body** (`{}`):\n\n", body.body_type));
                md.push_str("```json\n");
                md.push_str(&body.content);
                if !body.content.ends_with('\n') {
                    md.push('\n');
                }
                md.push_str("```\n\n");
            }
        }

        md.push_str("---\n\n");
    }

    md
}

fn generate_html(collection_name: &str, requests: &[DocRequest]) -> String {
    let mut html = String::new();

    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str(&format!("<title>{collection_name} — API Docs</title>\n"));
    html.push_str("<style>\n");
    html.push_str(CSS_STYLES);
    html.push_str("</style>\n</head>\n<body>\n");

    html.push_str(&format!("<h1>{collection_name}</h1>\n"));
    html.push_str(&format!(
        "<p class=\"meta\">Generated by ApiArk on {}</p>\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));

    // TOC
    html.push_str("<nav class=\"toc\"><h2>Endpoints</h2><ul>\n");
    for (i, doc) in requests.iter().enumerate() {
        let method = format!("{:?}", doc.request.method).to_uppercase();
        let folder_prefix = if doc.folder.is_empty() {
            String::new()
        } else {
            format!("{} / ", doc.folder)
        };
        html.push_str(&format!(
            "<li><a href=\"#req-{i}\"><span class=\"method method-{m}\">{method}</span> {folder_prefix}{}</a></li>\n",
            doc.request.name,
            m = method.to_lowercase()
        ));
    }
    html.push_str("</ul></nav>\n");

    // Requests
    let mut current_folder = String::new();

    for (i, doc) in requests.iter().enumerate() {
        if doc.folder != current_folder {
            current_folder = doc.folder.clone();
            if !current_folder.is_empty() {
                html.push_str(&format!("<h2 class=\"folder\">{current_folder}</h2>\n"));
            }
        }

        let req = &doc.request;
        let method = format!("{:?}", req.method).to_uppercase();

        html.push_str(&format!(
            "<section id=\"req-{i}\" class=\"endpoint\">\n"
        ));
        html.push_str(&format!(
            "<h3><span class=\"method method-{m}\">{method}</span> <code>{}</code></h3>\n",
            html_escape(&req.url),
            m = method.to_lowercase()
        ));

        if let Some(desc) = &req.description {
            if !desc.is_empty() {
                html.push_str(&format!("<p class=\"desc\">{}</p>\n", html_escape(desc)));
            }
        }

        // Headers
        if !req.headers.is_empty() {
            html.push_str("<h4>Headers</h4>\n<table><thead><tr><th>Header</th><th>Value</th></tr></thead><tbody>\n");
            for (k, v) in &req.headers {
                html.push_str(&format!(
                    "<tr><td><code>{}</code></td><td><code>{}</code></td></tr>\n",
                    html_escape(k),
                    html_escape(v)
                ));
            }
            html.push_str("</tbody></table>\n");
        }

        // Params
        if let Some(params) = &req.params {
            if !params.is_empty() {
                html.push_str("<h4>Query Parameters</h4>\n<table><thead><tr><th>Parameter</th><th>Value</th></tr></thead><tbody>\n");
                for (k, v) in params {
                    html.push_str(&format!(
                        "<tr><td><code>{}</code></td><td><code>{}</code></td></tr>\n",
                        html_escape(k),
                        html_escape(v)
                    ));
                }
                html.push_str("</tbody></table>\n");
            }
        }

        // Body
        if let Some(body) = &req.body {
            if !body.content.is_empty() {
                html.push_str(&format!(
                    "<h4>Request Body <span class=\"body-type\">({})</span></h4>\n",
                    html_escape(&body.body_type)
                ));
                html.push_str(&format!(
                    "<pre><code>{}</code></pre>\n",
                    html_escape(&body.content)
                ));
            }
        }

        html.push_str("</section>\n");
    }

    html.push_str("<footer>Generated by <a href=\"https://apiark.dev\">ApiArk</a></footer>\n");
    html.push_str("</body>\n</html>\n");
    html
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const CSS_STYLES: &str = r#"
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; background: #0a0a0b; color: #e4e4e7; }
h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
h2 { font-size: 1.3rem; margin-top: 2rem; margin-bottom: 1rem; color: #a1a1aa; border-bottom: 1px solid #2a2a2e; padding-bottom: 0.5rem; }
h3 { font-size: 1rem; margin-bottom: 0.5rem; }
h4 { font-size: 0.85rem; margin: 1rem 0 0.5rem; color: #a1a1aa; }
.meta { color: #71717a; font-size: 0.85rem; margin-bottom: 2rem; }
.toc { background: #141416; border: 1px solid #2a2a2e; border-radius: 8px; padding: 1rem 1.5rem; margin-bottom: 2rem; }
.toc h2 { margin: 0 0 0.5rem; border: none; padding: 0; font-size: 1rem; }
.toc ul { list-style: none; }
.toc li { padding: 0.25rem 0; }
.toc a { color: #e4e4e7; text-decoration: none; font-size: 0.85rem; }
.toc a:hover { color: #3b82f6; }
.method { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 700; font-family: monospace; }
.method-get { background: #22c55e20; color: #22c55e; }
.method-post { background: #eab30820; color: #eab308; }
.method-put { background: #3b82f620; color: #3b82f6; }
.method-patch { background: #a855f720; color: #a855f7; }
.method-delete { background: #ef444420; color: #ef4444; }
.method-head { background: #06b6d420; color: #06b6d4; }
.method-options { background: #6b728020; color: #6b7280; }
.endpoint { background: #141416; border: 1px solid #2a2a2e; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
.desc { color: #a1a1aa; margin: 0.5rem 0; font-size: 0.9rem; }
table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #2a2a2e; }
th { color: #71717a; font-weight: 500; }
code { font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 0.85em; }
pre { background: #1c1c1f; border: 1px solid #2a2a2e; border-radius: 6px; padding: 1rem; overflow-x: auto; font-size: 0.85rem; }
.body-type { font-size: 0.75rem; color: #71717a; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #2a2a2e; color: #71717a; font-size: 0.8rem; text-align: center; }
footer a { color: #3b82f6; text-decoration: none; }
"#;
